= Benchmarks

== How to run

You need to have Java 11 to run the benchmarks. The Exec Maven Plugin will run the benschmarks.jar file to start the benchmarking process:

```
$ cd benchmarks
$ mvn clean install exec:exec
```

Outside Maven after building the benchmarks.jar you can just run:

```
$ cd benchmarks
$ java -jar target/benchmarks.jar
```

= Results

== macBook Lofi Dewanto Result April 2020
- CPU: 2.7 GHz Quad-Core Intel Core i7
- Memory: 16 GB 2133 MHz LPDDR3

=== AspectJ 1.9.5, OpenJDK 11, JMH 1.23, Spring Boot 2.2.4

```
Result "com.bench.StartupBenchmark.spring":
  3,539 ±(99.9%) 0,390 s/op [Average]
  (min, avg, max) = (3,173, 3,539, 3,885), stdev = 0,258
  CI (99.9%): [3,149, 3,929] (assumes normal distribution)

# Run complete. Total time: 00:29:58

REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
experiments, perform baseline and negative tests that provide experimental control, make sure
the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
Do not assume the numbers tell you what you want them to tell.

Benchmark                 (scale)  Mode  Cnt  Score   Error  Units
StartupBenchmark.ltw          N/A  avgt   10  2,467 ± 0,256   s/op
StartupBenchmark.ltw_100      N/A  avgt   10  2,742 ± 0,530   s/op
StartupBenchmark.spring     v0_10  avgt   10  1,707 ± 0,090   s/op
StartupBenchmark.spring     v1_10  avgt   10  2,098 ± 0,923   s/op
StartupBenchmark.spring    v1_100  avgt   10  2,031 ± 0,169   s/op
StartupBenchmark.spring    v10_50  avgt   10  2,885 ± 0,303   s/op
StartupBenchmark.spring    v20_50  avgt   10  3,961 ± 0,466   s/op
StartupBenchmark.spring     a0_10  avgt   10  2,304 ± 0,445   s/op
StartupBenchmark.spring     a1_10  avgt   10  2,652 ± 0,692   s/op
StartupBenchmark.spring    a1_100  avgt   10  2,666 ± 0,491   s/op
StartupBenchmark.spring    a10_50  avgt   10  3,087 ± 0,277   s/op
StartupBenchmark.spring   a10_100  avgt   10  3,379 ± 1,037   s/op
StartupBenchmark.spring    a20_50  avgt   10  3,539 ± 0,390   s/op
```

=== AspectJ 1.9.2, Oracle JDK 1.8, JMH 1.16, Spring Boot 2.1.1

```
Result "spring":
  2,918 ±(99.9%) 0,056 s/op [Average]
  (min, avg, max) = (2,862, 2,918, 2,971), stdev = 0,037
  CI (99.9%): [2,862, 2,975] (assumes normal distribution)

# Run complete. Total time: 00:06:06

Benchmark                 (scale)  Mode  Cnt  Score    Error  Units
StartupBenchmark.ltw          N/A  avgt   10  0,017 ±  0,001   s/op
StartupBenchmark.ltw_100      N/A  avgt   10  0,017 ±  0,001   s/op
StartupBenchmark.spring     v0_10  avgt   10  2,158 ±  0,131   s/op
StartupBenchmark.spring     v1_10  avgt   10  2,235 ±  0,056   s/op
StartupBenchmark.spring    v1_100  avgt   10  2,273 ±  0,076   s/op
StartupBenchmark.spring    v10_50  avgt   10  2,908 ±  0,055   s/op
StartupBenchmark.spring    v20_50  avgt   10  3,622 ±  0,041   s/op
StartupBenchmark.spring     a0_10  avgt   10  2,083 ±  0,054   s/op
StartupBenchmark.spring     a1_10  avgt   10  2,183 ±  0,040   s/op
StartupBenchmark.spring    a1_100  avgt   10  2,219 ±  0,041   s/op
StartupBenchmark.spring    a10_50  avgt   10  2,539 ±  0,044   s/op
StartupBenchmark.spring   a10_100  avgt   10  2,567 ±  0,034   s/op
StartupBenchmark.spring    a20_50  avgt   10  2,918 ±  0,056   s/op
```

== Older Results

=== AspectJ 1.8.11 Snapshots

(Seems to fix the problem with Spring AOP.)

```
Benchmark                 (scale)  Mode  Cnt  Score   Error  Units
StartupBenchmark.ltw          N/A  avgt   10  1.878 ± 0.039   s/op
StartupBenchmark.ltw_100      N/A  avgt   10  1.930 ± 0.083   s/op
StartupBenchmark.spring     v0_10  avgt   10  1.485 ± 0.033   s/op
StartupBenchmark.spring     v1_10  avgt   10  1.605 ± 0.069   s/op
StartupBenchmark.spring    v1_100  avgt   10  1.629 ± 0.022   s/op
StartupBenchmark.spring    v10_50  avgt   10  2.176 ± 0.091   s/op
StartupBenchmark.spring    v20_50  avgt   10  2.771 ± 0.080   s/op
StartupBenchmark.spring     a0_10  avgt   10  1.485 ± 0.049   s/op
StartupBenchmark.spring     a1_10  avgt   10  1.564 ± 0.032   s/op
StartupBenchmark.spring    a1_100  avgt   10  1.603 ± 0.047   s/op
StartupBenchmark.spring    a10_50  avgt   10  1.831 ± 0.013   s/op
StartupBenchmark.spring   a10_100  avgt   10  1.890 ± 0.060   s/op
StartupBenchmark.spring    a20_50  avgt   10  2.121 ± 0.083   s/op
```

=== AspectJ 1.8.10

```
Benchmark                        Mode  Cnt   Score   Error  Units
StartupBenchmark.null            avgt   10   2.114 ± 0.134   s/op
StartupBenchmark.ltw             avgt   10   2.749 ± 0.067   s/op
StartupBenchmark.ltw_10          avgt   10   2.914 ± 0.110   s/op
StartupBenchmark.ltw_10_100      avgt   10   2.873 ± 0.114   s/op
StartupBenchmark.ltw_20          avgt   10   2.900 ± 0.110   s/op
StartupBenchmark.ltw_20_100      avgt   10   2.965 ± 0.114   s/op
StartupBenchmark.annotation         avgt   10   2.113 ± 0.095   s/op
StartupBenchmark.annotation_10_100  avgt   10   7.204 ± 0.062   s/op
StartupBenchmark.annotation_10_50   avgt   10   7.199 ± 0.092   s/op
StartupBenchmark.annotation_1_100   avgt   10   2.838 ± 0.115   s/op
StartupBenchmark.annotation_1_50    avgt   10   2.814 ± 0.070   s/op
StartupBenchmark.annotation_20_100  avgt   10  11.512 ± 0.106   s/op
StartupBenchmark.annotation_20_50   avgt   10  11.476 ± 0.132   s/op
```

.Number of @Aspects vs. Startup Time
image::https://docs.google.com/spreadsheets/d/e/2PACX-1vR8B4l5WkWf-9gZWmIYTkmBWM7YWf5bRg852OakrV0G2-vtfM_UkVNRC3cTVk1079HagnMVHYZnvbib/pubchart?oid=756916910&amp;format=image[]

Legend:

* null:           No aspect weaving at all.
* annotation:        Spring AOP. No aspects with method annotation pointcuts.
* annotation_1_50:   Spring AOP with extra aspects(1) and beans(50).
* annotation_1_100:  Spring AOP with extra aspects(1) and beans(100).
* annotation_10_50:  Spring AOP with extra aspects(10) and beans(50).
* annotation_10_50:  Spring AOP with extra aspects(10) and beans(100).
* annotation_20_50:  Spring AOP with extra aspects(20) and beans(50).
* annotation_20_50:  Spring AOP with extra aspects(20) and beans(100).
* ltw:            Load Time Weaving. Aspects woven by AspectJ agent, not Spring.
* ltw_10:         Load Time Weaving with extra aspects (10).
* ltw_10_100:     Load Time Weaving with extra aspects(10) and beans(100).
* ltw_20:         Load Time Weaving with extra aspects (20).
* ltw_20_100:     Load Time Weaving with extra aspects(20) and beans(100).

|===
| sample | @aspects | beans | startup(millis)

| null           | 0 | 188 | 2117
| ltw            | 0 | 188 | 2749
| ltw_10         | 10| 188 | 2914
| ltw_10_100     | 10| 288 | 2873
| ltw_20         | 20| 188 | 2900
| ltw_20_100     | 20| 288 | 2965
| annotation        | 0 | 191 | 2113
| annotation_1_50   | 1 | 242 | 2814
| annotation_1_100  | 1 | 292 | 2838
| annotation_10_50  | 10| 251 | 7119
| annotation_10_100 | 10| 301 | 7204
| annotation_20_50  | 20| 261 | 11476
| annotation_20_100 | 20| 311 | 11512


|===

The annotation (Spring AOP) samples are much slower with @aspects than
without and the slow down is proportional to the number of pointcuts
(not so much with the number of beans). It's pretty awful: 400ms per
pointcut.

The "ltw" samples are a bit slower with @aspects than without, but the
slow down is not proportional to the number of pointcuts. Note,
however, that all the pointcuts were the same, so maybe there is some
optimization in AspectJ that doesn't help for a realistic system.
